--- #YAML:1.0
name:                Net-Connection-Sniffer
version:             0.29
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Net::DNS::Codes:               0.09
    Net::DNS::ToolKit:             0.41
    Net::Interface:                1.008
    Net::NBsocket:                 0.14
    NetAddr::IP:                   4.024
    Proc::PidUtil:                 0.08
    Sys::Hostname::FQDN:           0.07
    Sys::Sig:                      0.03
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
