# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Connection-Sniffer
version:      0.22
version_from: Sniffer.pm
installdirs:  site
requires:
    Net::DNS::Codes:               0.08
    Net::DNS::ToolKit:             0.26
    Net::Interface:                0.08
    Net::NBsocket:                 0.12
    NetAddr::IP::Util:             0.11
    Proc::PidUtil:                 0.07
    Sys::Hostname::FQDN:           0.07
    Sys::Sig:                      0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
