# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Connection-Sniffer
version:      0.09
version_from: Sniffer.pm
installdirs:  site
requires:
    NetAddr::IP::Util:             0.07
    Proc::PidUtil:                 0.07
    Sys::Sig:                      0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
