--- #YAML:1.0
name:                Net-Connection-Sniffer
version:             0.25
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Net::DNS::Codes:               0.08
    Net::DNS::ToolKit:             0.26
    Net::Interface:                0.08
    Net::NBsocket:                 0.12
    NetAddr::IP::Util:             0.11
    Proc::PidUtil:                 0.07
    Sys::Hostname::FQDN:           0.07
    Sys::Sig:                      0.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
